version: '3'  
services:  
  app:
    build: .
    volumes:
      - .:/var/lib/code
    depends_on:
      - db
    links:
      - db

  db:
    image: influxdb
    volumes:
      - ./db_data:/var/lib/influxdb
    ports:
      - 8086:8086

  visual:
    image: grafana/grafana:5.0.4
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
